---
deployment:
  tasks:
    - /bin/mkdir -p /home3/startech/public_html/crm
    - /bin/rm -rf /home3/startech/public_html/crm/assets
    - /bin/cp -R index.html .htaccess assets api cron install /home3/startech/public_html/crm/
